#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#AutoStart
pkill conky
feh --bg-fill ~/Pictures/wallpapers/space-mars-4480x2520-nordified.jpg #wallpaper location
picom & #compositor
conky #the cool thing on the right side of the screen lol
bash ~/.config/polybar/launch.sh --blocks #polybar
dunst #notification
notify-send "insert text here"
